stages:
  - deploy

deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  environment: production
  script:
    # Authenticate with GCP using a service account key
    - echo $GCP_SERVICE_ACCOUNT_KEY > key.json
    - gcloud auth activate-service-account --key-file=key.json
    # Configure kubectl to use GKE cluster
    - gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_CLUSTER_ZONE --project $GCP_PROJECT_ID
    # Create a new deployment with the specified image
    - kubectl create deployment simple-springboot-app --image=$CI_REGISTRY_IMAGE:latest
